language: rust
rust: nightly
notifications:
  email:
    on_success: never
env:
  global:
    - secure: K0gSlZrFNPwsxfoAaRrSu+rV5ODV0a0SbINwrOYB1U11lXb35Q3IBcXLlqVu7a46dnoVyLek/OUjAgxYwq2sVf5NtQFZtPCgda51LXnhKrloPRFjRdlnYEMwDcxkIotQoPShHWV3KwuZz1YIUquo3GzkAft8GqruQcPt9zhr0zY=
script:
  - ./cargo_util.py --test
  - ./cargo_util.py --doc
after_success:
  - cd doc/target
  - ../gh_pages_upload.sh
