language: rust
notifications:
  email:
    on_success: never
script:
  - cd slr_lexer
  - cargo test
  - ./target/debug/examples/lexer_test ../test/test.slr
  - cd ../slr_config
  - cargo test
  - ./target/debug/examples/slr_test ../test/test.slr
