[package]

name = "doc"
version = "0.0.21" #auto
authors = [ "SiegeLord <slabode@aim.com>" ]

[lib]
name = "delete_me"
path = "dummy.rs"

[dependencies.slr_parser]

path = "../slr_parser"
version = "=0.0.21" #auto

[dependencies.slr_config]

path = "../slr_config"
version = "=0.0.21" #auto
